container:
  dockerfile: Dockerfile
  cpu: 8
  memory: 24

.build_env_template: &build_env_template
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  BB_NUMBER_THREADS: 8
  PARALLEL_MAKE: -j 4
  GITHUB_TOKEN_FOR_CIRRUSCI: ENCRYPTED[b616f030c6538608b10312b0b1959e48e7c635c360d18888e5d82ebf19e1bbf410e035d699b5a686f907afe85712aa98]


.build_template: &build_template
  timeout_in: 120m
  build_script:
    - mkdir -p pedalpi-src-build/images/$TARGET/
    - echo XXX > pedalpi-src-build/images/$TARGET/pedalpi-dev-platform-$TARGET-XXX.rootfs.sunxi-sdimg
    - find
    - curl --version
#  only_if: $BRANCH == "master"
  publish_script:
    - filename=$(ls pedalpi-src-build/images/nanopi-neo-air/pedalpi-dev-platform-nanopi-neo-air-*.rootfs.sunxi-sdimg)
    - bash ./upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN_FOR_CIRRUSCI owner=auto3000 repo=pedalpi-dev-platform tag=LATEST filename=$filename

build_raspberrypi3_task:
  <<: *build_template
  env:
    <<: *build_env_template
    TARGET: raspberrypi3

build_raspberrypi2_task:
  <<: *build_template
  env:
    <<: *build_env_template
    TARGET: raspberrypi2

build_qemux86-64_task:
  <<: *build_template
  env:
    <<: *build_env_template
    TARGET: qemux86-64

build_nanopi-neo-air_task:
  <<: *build_template
  env:
    <<: *build_env_template
    TARGET: nanopi-neo-air

