container:
  image: crops/yocto:ubuntu-14.04-builder
  cpu: 8
  memory: 24

.build_env_template: &build_env_template
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  BB_NUMBER_THREADS: 8
  PARALLEL_MAKE: -j 4


.build_template: &build_template
  script:
    - source init.sh $TARGET
    - echo 'SCONF_VERSION = "1"'  > conf/site.conf
    - echo 'SSTATE_DIR ?= "/tmp/sstate-cache"' >> conf/site.conf
    - echo 'DL_DIR ?= "/tmp/downloads"' >> conf/site.conf
    - mkdir -p tmp/deploy/images/
    - if [[ $CIRRUS_TASK_NAME =~ .*step.* ]]; then
    -   timeout -k 720 560 bash -c "bitbake pedalpi-dev-platform | cat -" || echo build is not finished yet
    - else
    -   bitbake pedalpi-dev-platform | cat -
    - fi


build_raspberrypi3_task:
  <<: *build_template
  env:
    <<: *build_env_template
    TARGET: raspberrypi3

build_raspberrypi2_task:
  <<: *build_template
  env:
    <<: *build_env_template
    TARGET: raspberrypi2

build_qemux86-64_task:
  <<: *build_template
  env:
    <<: *build_env_template
    TARGET: qemux86-64

build_nanopi-neo-air_task:
  <<: *build_template
  env:
    <<: *build_env_template
    TARGET: nanopi-neo-air
