pool:
  vmImage: 'ubuntu-16.04'

container: crops/yocto


steps:
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      source init.sh nanopi-neo-air
      echo 'SCONF_VERSION = "1"' > conf/site.conf
      echo 'SSTATE_DIR ?= "/tmp/sstate-cache"' >> conf/site.conf
      echo 'DL_DIR ?= "/tmp/downloads"' >> conf/site.conf
      bitbake pedalpi-dev-platform | cat -
    displayName: 'Run a multi-line script'


