pool:
  vmImage: 'ubuntu-16.04'

resources:
  containers:
    - container: crops_poky
      image: 'auto3000/poky'
      env:
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8

container: crops_poky

jobs:
- job: A
  displayName: 'Run a multi-line script'
  timeoutInMinutes: 0
  steps:
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      source init.sh nanopi-neo-air
      echo 'SCONF_VERSION = "1"' > conf/site.conf
      echo 'SSTATE_DIR ?= "/tmp/sstate-cache"' >> conf/site.conf
      echo 'DL_DIR ?= "/tmp/downloads"' >> conf/site.conf
      bitbake pedalpi-dev-platform | cat -
- job: B
  dependsOn: A
  steps:
    - script: echo hello from B


