
resources:
  containers:
  - container: crops_poky
    image: 'auto3000/poky'
    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      BB_NUMBER_THREADS: 4
      PARALLEL_MAKE: -j 8 

jobs:
- job: build_qemux86_64
  displayName: 'build_qemux86_64'
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-16.04'
  container: crops_poky
  steps:
    - script: |
        source init.sh qemux86-64
        echo 'SCONF_VERSION = "1"' > conf/site.conf
        echo 'SSTATE_DIR ?= "/tmp/sstate-cache"' >> conf/site.conf
        echo 'DL_DIR ?= "/tmp/downloads"' >> conf/site.conf
        bitbake pedalpi-dev-platform
        if [ $BUILD_SOURCEBRANCH != "refs/heads/master" ]; then
          echo "Publish release to GitHub"
          filename=$(ls tmp/deploy/images/qemux86-64/pedalpi-dev-platform-qemux86-64-*.rootfs.tar.bz2)
          bash ./upload-github-release-asset.sh github_api_token=$(GitHubTokenForAzurePipeline) owner=auto3000 repo=pedalpi-dev-platform tag=LATEST filename="$filename"
        fi
- job: build_raspberrypi2
  displayName: 'build_raspberrypi2'
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-16.04'
  container: crops_poky
  steps:
    - script: |
        source init.sh raspberrypi2
        echo 'SCONF_VERSION = "1"' > conf/site.conf
        echo 'SSTATE_DIR ?= "/tmp/sstate-cache"' >> conf/site.conf
        echo 'DL_DIR ?= "/tmp/downloads"' >> conf/site.conf
        bitbake pedalpi-dev-platform
        if [ $BUILD_SOURCEBRANCH != "refs/heads/master" ]; then
          echo "Publish release to GitHub"
          filename=$(ls tmp/deploy/images/raspberrypi2/pedalpi-dev-platform-raspberrypi2-*.rootfs.rpi-sdimg)
          bash ./upload-github-release-asset.sh github_api_token=$(GitHubTokenForAzurePipeline) owner=auto3000 repo=pedalpi-dev-platform tag=LATEST filename="$filename"
        fi
- job: build_raspberrypi3
  displayName: 'build_raspberrypi3'
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-16.04'
  container: crops_poky
  steps:
    - script: |
        source init.sh raspberrypi2
        echo 'SCONF_VERSION = "1"' > conf/site.conf
        echo 'SSTATE_DIR ?= "/tmp/sstate-cache"' >> conf/site.conf
        echo 'DL_DIR ?= "/tmp/downloads"' >> conf/site.conf
        bitbake pedalpi-dev-platform
        if [ $BUILD_SOURCEBRANCH != "refs/heads/master" ]; then
          echo "Publish release to GitHub"
          filename=$(ls tmp/deploy/images/raspberrypi3/pedalpi-dev-platform-raspberrypi3-*.rootfs.rpi-sdimg)
          bash ./upload-github-release-asset.sh github_api_token=$(GitHubTokenForAzurePipeline) owner=auto3000 repo=pedalpi-dev-platform tag=LATEST filename="$filename"
        fi
- job: build_nanopi_neo_air
  displayName: 'build_nanopi-neo-air'
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-16.04'
  container: crops_poky
  steps:
    - script: |
        source init.sh raspberrypi2
        echo 'SCONF_VERSION = "1"' > conf/site.conf
        echo 'SSTATE_DIR ?= "/tmp/sstate-cache"' >> conf/site.conf
        echo 'DL_DIR ?= "/tmp/downloads"' >> conf/site.conf
        bitbake pedalpi-dev-platform
        if [ $BUILD_SOURCEBRANCH != "refs/heads/master" ]; then
          echo "Publish release to GitHub"
          filename=$(ls /tmp/deploy/images/nanopi-neo-air/pedalpi-dev-platform-nanopi-neo-air-*.rootfs.sunxi-sdimg)
          bash ./upload-github-release-asset.sh github_api_token=$(GitHubTokenForAzurePipeline) owner=auto3000 repo=pedalpi-dev-platform tag=LATEST filename="$filename"
        fi
