
resources:
  containers:
  - container: crops_poky
    image: 'auto3000/poky'
    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      GITHUB_TOKEN_FOR_AZUREPIPELINE: $(GitHubTokenForAzurePipeline)

jobs:
- job: build_qemux86_64
  displayName: 'build_qemux86_64'
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-16.04'
  container: crops_poky
  steps:
    - script: |
        if [ $BUILD_SOURCEBRANCH != "refs/heads/master" ]; then
          echo "Publish release to GitHub"
          filename=$(ls images/qemux86-64/pedalpi-dev-platform-qemux86-64-*.rootfs.tar.bz2)
          bash ./upload-github-release-asset.sh github_api_token=$(GitHubTokenForAzurePipeline) owner=auto3000 repo=pedalpi-dev-platform tag=LATEST filename="$filename"
        fi
